# Generated by Django 4.2.6 on 2023-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short_app', '0002_alter_urldata_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='longUrl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='shortUrl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
